version: '3.3'
services:
  arthas-tunnel-server:
    image: registry.cn-hangzhou.aliyuncs.com/ywja/arthas-tunnel-server:master
    network_mode: host
    restart: unless-stopped
    environment:
      USERNAME: test
      USER_PASSWORD: test
      WS_PORT: 19998
      SERVER_PORT: 19999
    container_name: 'arthas-tunnel-server-master'